// data dummy karyawan
const DataKaryawan = [
  {
    id: 1,
    nama: "DONI HERAWAN",
    nip: 12032,
    jabatan: "Fullstack Developer",
    alamat: "Jl. Dago",
    phone: "+6282330602071",
    email: "doni@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 2,
    nama: "RETNO PRIH ASTUTI",
    nip: 12242,
    jabatan: "Frontend Developer",
    alamat: "Jl. Antapani",
    phone: "+6283871576645",
    email: "retno@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 3,
    nama: "BUDI NATULYATI",
    nip: 12251,
    jabatan: "Backend Developer",
    alamat: "Jl. Buahbatu",
    phone: "+6281286616893",
    email: "budi@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 4,
    nama: "APRINA SATWATI",
    nip: 30420,
    jabatan: "UI/UX Designer",
    alamat: "Jl. Kiaracondong",
    phone: "+6283870239357",
    email: "aprina@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 5,
    nama: "SULARDI",
    nip: 91720,
    jabatan: "System Engineer",
    alamat: "Jl. Lembang",
    phone: "+6281219550857",
    email: "sulardi@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 6,
    nama: "DWI AGUSTINA",
    nip: 12272,
    jabatan: "Network Engineer",
    alamat: "Jl. Setiabudi",
    phone: "+6283870815121",
    email: "dwiagustina@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 7,
    nama: "WANDA ERMA AGUSTINA",
    nip: 31120,
    jabatan: "Mobile Developer",
    alamat: "Jl. Sarijadi",
    phone: "+6285282470182",
    email: "wanda@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 8,
    nama: "SEPTIAN ARISTIANTO",
    nip: 51020,
    jabatan: "Data Analyst",
    alamat: "Jl. Ambon",
    phone: "+6282347126017",
    email: "septian@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 9,
    nama: "PARWANTO",
    nip: 80720,
    jabatan: "Financial Advisor",
    alamat: "Jl. Riau",
    phone: "+6281284123448",
    email: "parwanto@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
  {
    id: 10,
    nama: "WAHYUDIARTO",
    nip: 42820,
    jabatan: "Accounting",
    alamat: "Jl. Laswi",
    phone: "+6281284123447",
    email: "wahyudiarto@gmail.com",
    foto: "images/avatar.png",
    createdAt: new Date().toISOString(),
    createdBy: "admin",

  },
]

module.exports = { DataKaryawan };